version: "3.2"

services:
  musiccast-repairkit:
    build: .
    image: nicolabs/musiccast-repairkit
    ports:
      - target: 41100
        published: 41100
        protocol: udp
        mode: host
    # Define SPEAKERS_IP, YAMAHA_IP in this .env file
    # Do not specify LOCAL_IP as it will probably fail to bind
    # inside the container, which has is own private IP range
    #env_file: .env
    deploy:
      mode: replicated
      replicas: 1
    logging:
      options:
        max-size: "200k"
        max-file: "10"
